approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmAuditRegistry: "https://registry.npmjs.org"

npmMinimalAgeGate: 0

npmPreapprovedPackages:
  - "@emnapi/*"
  - "@napi-rs/*"
  - "@oxlint/*"
  - "@oxfmt/*"
  - "@oxc-node/*"
  - emnapi
  - oxfmt
  - oxlint

yarnPath: .yarn/releases/yarn-4.18.1.cjs
