/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * Converts an encoded image to WebP.
 *
 * The input format is detected from its magic bytes. Animated GIFs become
 * animated WebP, keeping frame delays and loop count; every other input
 * becomes a still WebP. Encoding runs on the libuv threadpool.
 *
 * Throws synchronously when `options` is invalid. The promise rejects when
 * the input cannot be decoded or encoded.
 */
export declare function convert(input: Buffer, options?: ConvertOptions | undefined | null): Promise<ConvertResult>

/**
 * Reads the image at `inputPath`, converts it to WebP and writes the result
 * to `outputPath`.
 *
 * Same conversion rules as `convert`. File IO also runs on the libuv
 * threadpool. Overwrites `outputPath` if it exists; its parent directory must
 * already exist.
 */
export declare function convertFile(
  inputPath: string,
  outputPath: string,
  options?: ConvertOptions | undefined | null,
): Promise<ConvertFileResult>

/** Result of `convertFile`. The WebP itself is written to `outputPath`. */
export interface ConvertFileResult {
  /** The quality the output was encoded at (0-100). */
  quality: number
  /** Number of frames in the output. 1 for a still image. */
  frameCount: number
}

/** Options for `convert` and `convertFile`. Every field is optional. */
export interface ConvertOptions {
  /**
   * Lowest quality the sweep tries, an integer from 0 to 100. Defaults to 80.
   * Ignored when `quality` is set.
   */
  minQuality?: number
  /**
   * Encode once at exactly this quality, an integer from 0 to 100, instead of
   * sweeping for the best size/quality ratio.
   */
  quality?: number
}

/** Result of `convert`. */
export interface ConvertResult {
  /** The WebP file contents. */
  data: Buffer
  /** The quality the output was encoded at (0-100). */
  quality: number
  /** Number of frames in the output. 1 for a still image. */
  frameCount: number
}
